spring.application.name=userservice

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgreY

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Logging
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %highlight(%-5level) - %logger{36} - %msg%n

logging.file.name=logs/app.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

logging.level.root=INFO
